create table example (
  id         integer generated by default as identity primary key,
  rank       integer not null,
  parity     varchar(255),
  created_at timestamp not null,
  updated_at timestamp not null
);
